update script with latest zenoh api
open-rmf/free_fleet pull request #149
Opened 2024-10-15 15:14 UTC by tomkimsour

## New feature implementation

### Implemented feature

Migrate zenoh to zenoh 1.0.0.b4

### Implementation description

2024-10-16 02:38 UTC, aaronchongth requested changes
Thanks for the huge help with the migration! Yes I was definitely planning to get to 1.0.0 soon, but was hesitant with it still being in beta, and free_fleet's lack of static and integration tests (it's WIP though!)

I've just done a first pass and left a few comments, I'll need to run some tests manually too. The merge conflict is most definitely from https://github.com/open-rmf/free_fleet/pull/146, where some minor tests and testing infra have been added

2024-10-16 02:38 UTC, aaronchongth commented on free_fleet_adapter/setup.py
> +        ),
I'm guessing this might be left over from your own project?

2024-10-16 02:38 UTC, aaronchongth commented on free_fleet_adapter/free_fleet_adapter/nav2_robot_adapter.py
> +        print("about to get the action")
We should probably remove testing printouts, unless you find it necessary, we could convert it into a `self.node.get_logger().debug(...`, with more information about the goal message

2024-10-16 02:38 UTC, aaronchongth commented on free_fleet_adapter/free_fleet_adapter/nav2_robot_adapter.py
> +        print("finished to get the action")
This looks to be a testing printout as well

2024-10-30 09:54 UTC, tomkimsour commented
NB: I've been testing with zenoh 1.0.0 and the upgrade does not seem to break anything

2024-10-30 10:23 UTC, davecrawley commented
Outstanding!!!

David

===================================================
Ubiquity Robotics, Inc. is honored to win the Silicon Valley Robotics
good robot industry award in the commercialization category.
Ubiquity Robotics wins SVR good robot industry award
<https://svrobo.org/ubiquity-robotics-wins-commercialization-award-in-svr-good-robot-industry-awards/>


On Wed, Oct 30, 2024 at 10:55 AM Thomas Ung ***@***.***>
wrote:

> NB: I've been testing with zenoh 1.0.0 and the upgrade does not seem to
> break anything
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/open-rmf/free_fleet/pull/149#issuecomment-2446386443>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYN4VQDDHWZ4FWQ6R3YOO3Z6CUH3AVCNFSM6AAAAABP7M3ZOGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBWGM4DMNBUGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-10-31 15:47 UTC, aaronchongth requested changes
Thanks for the updates! I've a few last comments, and after linting is fixed, we should be good to merge.

edit: adding the job logs, https://github.com/open-rmf/free_fleet/actions/runs/11368807346/job/32189477205

2024-11-07 03:58 UTC, merged

2024-11-07 10:55 UTC, tomkimsour commented on README.md
> +* [zenoh-bridge-ros2dds v1.0.0-beta.4](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/releases/tag/1.0.0-beta.4)
yes, sorry I didn't see that comment, I'm using 1.0.0 now and it is indeed working the same way

2024-11-07 10:55 UTC, tomkimsour commented on README.md
> +* [zenoh-bridge-ros2dds v1.0.0-beta.4](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/releases/tag/1.0.0-beta.4)
should it be reverted and fixed ?